name: image-manipulation-api
type: worker

features:
  - buildpack-stack=ubuntu-20

http_port: 5000

build:
  commands:
    - apt-get update
    - apt-get install -y libgl1-mesa-glx
    - pip install -r requirements.txt

run:
  command: gunicorn app:app --worker-class gevent --timeout 60 --workers 2

envs:
  - key: FLASK_APP
    value: app.py
